Add logging step to create deployment workflow sections

diff --git a/.github/workflows/cli-scripts-deploy-custom-container-triton-single-model.yml b/.github/workflows/cli-scripts-deploy-custom-container-triton-single-model.yml
--- a/.github/workflows/cli-scripts-deploy-custom-container-triton-single-model.yml
+++ b/.github/workflows/cli-scripts-deploy-custom-container-triton-single-model.yml
@@ -45,5 +45,29 @@ jobs:
       run: |
           source "${{ github.workspace }}/infra/bootstrapping/sdk_helpers.sh";
           source "${{ github.workspace }}/infra/bootstrapping/init_environment.sh";
-          set -e; bash -x deploy-custom-container-triton-single-model.sh
+          log_output=$(set -e; bash -x deploy-custom-container-triton-single-model.sh 2>&1)
+          echo "$log_output" > sample.log
+          cat sample.log
       working-directory: cli
+    - name: Determine Failure Reason
+      run: |
+        failure_reason="N/A"
+        if [ "${{ job.status }}" == "failure" ]; then
+          if grep -q "ResourceNotReady" sample.log; then
+            failure_reason = "ResourceNotReady"
+          elif grep -q "quota" sample.log; then
+            failure_reason="QuotaIssue"
+          elif grep -q "ParentResourceNotFound" sample.log; then
+            failure_reason="ParentResourceNotFound"
+          else
+            failure_reason="UncategorizedFailure"
+          fi
+        fi
+        echo "FAILURE_REASON=$failure_reason" >> $GITHUB_ENV
+      working-directory: cli
+    - name: Log Job Results to Application Insights
+      uses: syedhassaanahmed/app-insights-event-action@main
+      with:
+        instrumentation-key: "${{ secrets.APP_INSIGHTS_INSTRUMENTATION_KEY }}"
+        event-name: "${{ job.status }}_${{ env.FAILURE_REASON }}"
+      if: always()
