edits

diff --git a/.github/workflows/cli-jobs-train-fastai-mnist-resnet18-fastai_mnist_job.yml b/.github/workflows/cli-jobs-train-fastai-mnist-resnet18-fastai_mnist_job.yml
--- a/.github/workflows/cli-jobs-train-fastai-mnist-resnet18-fastai_mnist_job.yml
+++ b/.github/workflows/cli-jobs-train-fastai-mnist-resnet18-fastai_mnist_job.yml
@@ -25,5 +25,20 @@ jobs:
       run: bash setup-workspace.sh
       working-directory: cli
     - name: create job
-      run: az ml job create -f jobs/train/fastai/mnist-resnet18/fastai_mnist_job.yml
+      run: |
+        job_id=`az ml job create -f jobs/train/fastai/mnist-resnet18/fastai_mnist_job.yml --query name -o tsv`
+        az ml job stream -n $job_id
+        status=`az ml job show -n $job_id --query status -o tsv`
+        echo $status
+        if [[ $status == "Completed" ]]
+        then
+          echo "Job completed"
+        elif [[ $status ==  "Failed" ]]
+        then
+          echo "Job failed"
+          exit 1
+        else 
+          echo "Job status not failed or completed"
+          exit 2
+        fi
       working-directory: cli
